# Resolução Primeira Lista de Exercícios
<ul>
    <li>Universidade Federal da Paraíba</li>
    <li>Tópicos Especiais em Computação Deep Learning</li>
    <li>Professor: Tiago Maritan</li>
    <li>Aluno: Matheus de Araújo Correia Lima Melo</li>
</ul>

## Questão 1

### Preparação dos dados

In [118]:
import numpy as np
from random import uniform
from sklearn.utils import shuffle
from sklearn.preprocessing import MinMaxScaler

In [119]:
train_labels = []
train_samples = []

"O problema pode ser formulado como um classificador de 8 padrões diferentes, sendo que cada padrão representa um vértice do cubo."
##### Sendo
<ul>
    <li>Padrão 1: x={0,0,0} com  vetor resposta d={ 1, 0, 0, 0, 0, 0, 0, 0}</li>
    <li>Padrão 2: x={0,0,1} com  vetor resposta d={ 0, 1, 0, 0, 0, 0, 0, 0}</li>
    <li>Padrão 3: x={0,1,0} com  vetor resposta d={ 0, 0, 1, 0, 0, 0, 0, 0}</li>
    <li>Padrão 4: x={0,1,1} com  vetor resposta d={ 0, 0, 0, 1, 0, 0, 0, 0}</li>
    <li>Padrão 5: x={1,0,0} com  vetor resposta d={ 0, 0, 0, 0, 1, 0, 0, 0}</li>
    <li>Padrão 6: x={1,0,1} com  vetor resposta d={ 0, 0, 0, 0, 0, 1, 0, 0}</li>
    <li>Padrão 7: x={1,1,0} com  vetor resposta d={ 0, 0, 0, 0, 0, 0, 1, 0}</li>
    <li>Padrão 8: x={1,1,1} com  vetor resposta d={ 0, 0, 0, 0, 0, 0, 0, 1}</li>    
</ul>
Devem ser considerados ruídos com raio de no máx 0.1, de forma que, se presentes, ainda sejam classificados corretamente.
Para tanto constrói-se a seguir um conjunto de 4000 exemplos de dados rótulados(500 para cada rótulo) para o problema:

In [120]:
vector_1 = [1, 0, 0, 0, 0, 0, 0, 0]
vector_2 = [0, 1, 0, 0, 0, 0, 0, 0]
vector_3 = [0, 0, 1, 0, 0, 0, 0, 0]
vector_4 = [0, 0, 0, 1, 0, 0, 0, 0]
vector_5 = [0, 0, 0, 0, 1, 0, 0, 0]
vector_6 = [0, 0, 0, 0, 0, 1, 0, 0]
vector_7 = [0, 0, 0, 0, 0, 0, 1, 0]
vector_8 = [0, 0, 0, 0, 0, 0, 0, 1]

In [121]:
for i in range(10):
    #Padrão 1 x= 0,0,0 -> Vetor Resposta 1
    random_1 = [0 + uniform(-1,1)*0.1, 0 + uniform(-1,1)*0.1, 0 + uniform(-1,1)*0.1]
    train_samples.append(random_1)
    train_labels.append(vector_1)
    
    #Padrão 2 x= 0,0,1 -> Vetor Resposta 2
    random_2 = [0 + uniform(-1,1)*0.1, 0 + uniform(-1,1)*0.1, 1 + uniform(-1,1)*0.1]
    train_samples.append(random_2)
    train_labels.append(vector_2)
    
    #Padrão 3 x= 0,1,0 -> Vetor Resposta 3
    random_3 = [0 + uniform(-1,1)*0.1, 1 + uniform(-1,1)*0.1, 0 + uniform(-1,1)*0.1]
    train_samples.append(random_3)
    train_labels.append(vector_3)
    
    #Padrão 4 x= 0,1,1 -> Vetor Resposta 4
    random_4 = [0 + uniform(-1,1)*0.1, 1 + uniform(-1,1)*0.1, 1 + uniform(-1,1)*0.1]
    train_samples.append(random_4)
    train_labels.append(vector_4)
    
    #Padrão 5 x= 1,0,0 -> Vetor Resposta 5
    random_5 = [1 + uniform(-1,1)*0.1, 0 + uniform(-1,1)*0.1, 0 + uniform(-1,1)*0.1]
    train_samples.append(random_5)
    train_labels.append(vector_5)
    
    #Padrão 6 x= 1,0,1 -> Vetor Resposta 6
    random_6 = [1 + uniform(-1,1)*0.1, 0 + uniform(-1,1)*0.1, 1 + uniform(-1,1)*0.1]
    train_samples.append(random_6)
    train_labels.append(vector_6)
    
    #Padrão 7 x= 1,1,0 -> Vetor Resposta 7
    random_7 = [1 + uniform(-1,1)*0.1, 1 + uniform(-1,1)*0.1, 0 + uniform(-1,1)*0.1]
    train_samples.append(random_7)
    train_labels.append(vector_7)
    
    #Padrão 8 x= 1,1,1 -> Vetor Resposta 8
    random_8 = [1 + uniform(-1,1)*0.1, 1 + uniform(-1,1)*0.1, 1 + uniform(-1,1)*0.1]
    train_samples.append(random_8)
    train_labels.append(vector_8)    

In [122]:
#Transformar os dados em numpy arrays para inserir na fit function
#Fazer o shuffle para evitar que a rede aprenda a ordem
train_labels = np.array(train_labels)
train_samples = np.array(train_samples)
train_labels, train_samples = shuffle(train_labels, train_samples)

### Modelo

In [123]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Activation, Dense
from tensorflow.keras.activations import hard_sigmoid
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.metrics import categorical_crossentropy

In [124]:
model = Sequential([
    Dense(units=8, input_shape=(3,), activation=hard_sigmoid)
])

In [125]:
model.summary()

Model: "sequential_9"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_21 (Dense)             (None, 8)                 32        
Total params: 32
Trainable params: 32
Non-trainable params: 0
_________________________________________________________________


In [126]:
model.compile(optimizer=Adam(learning_rate=0.01), loss=categorical_crossentropy, metrics=['accuracy'])

In [127]:
model.fit(x=train_samples, y=train_labels, validation_split=0.2, batch_size=10, epochs=28, shuffle=True, verbose=2)

Epoch 1/28
7/7 - 0s - loss: 2.0619 - accuracy: 0.1719 - val_loss: 2.0647 - val_accuracy: 0.0625
Epoch 2/28
7/7 - 0s - loss: 2.0301 - accuracy: 0.1719 - val_loss: 2.0344 - val_accuracy: 0.0625
Epoch 3/28
7/7 - 0s - loss: 2.0011 - accuracy: 0.1406 - val_loss: 2.0054 - val_accuracy: 0.0625
Epoch 4/28
7/7 - 0s - loss: 1.9727 - accuracy: 0.1562 - val_loss: 1.9773 - val_accuracy: 0.1875
Epoch 5/28
7/7 - 0s - loss: 1.9439 - accuracy: 0.2031 - val_loss: 1.9517 - val_accuracy: 0.1875
Epoch 6/28
7/7 - 0s - loss: 1.9146 - accuracy: 0.2969 - val_loss: 1.9232 - val_accuracy: 0.1875
Epoch 7/28
7/7 - 0s - loss: 1.8853 - accuracy: 0.3281 - val_loss: 1.8940 - val_accuracy: 0.1875
Epoch 8/28
7/7 - 0s - loss: 1.8567 - accuracy: 0.3438 - val_loss: 1.8674 - val_accuracy: 0.1875
Epoch 9/28
7/7 - 0s - loss: 1.8249 - accuracy: 0.3594 - val_loss: 1.8387 - val_accuracy: 0.2500
Epoch 10/28
7/7 - 0s - loss: 1.7952 - accuracy: 0.4062 - val_loss: 1.8110 - val_accuracy: 0.2500
Epoch 11/28
7/7 - 0s - loss: 1.7647 - a

## Questão 2

## a)

### Preparação dos dados

In [128]:
xor_samples = [[0,0],[0,1],[1,0],[1,1]]
xor_labels = [[0],[1],[1],[0]]

In [129]:
#Transformar os dados em numpy arrays para inserir na fit function
#Fazer o shuffle para evitar que a rede aprenda a ordem
xor_samples = np.array(xor_samples)
xor_labels = np.array(xor_labels)
xor_labels, xor_samples = shuffle(xor_labels, xor_samples)

### Modelo

In [130]:
model_2 = Sequential([
    Dense(units=4, input_shape=(2,), activation='relu'),
    Dense(units=3, activation='tanh'),    
    Dense(units=1, activation='sigmoid'),
])

In [131]:
model_2.summary()

Model: "sequential_10"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_22 (Dense)             (None, 4)                 12        
_________________________________________________________________
dense_23 (Dense)             (None, 3)                 15        
_________________________________________________________________
dense_24 (Dense)             (None, 1)                 4         
Total params: 31
Trainable params: 31
Non-trainable params: 0
_________________________________________________________________


In [132]:
model_2.compile(optimizer=Adam(learning_rate=0.1), loss='binary_crossentropy', metrics=['accuracy'])

In [133]:
model_2.fit(x=xor_samples, y=xor_labels, batch_size=4, epochs=100, shuffle=True, verbose=2)

Epoch 1/100
1/1 - 0s - loss: 0.7252 - accuracy: 0.7500
Epoch 2/100
1/1 - 0s - loss: 0.6797 - accuracy: 0.7500
Epoch 3/100
1/1 - 0s - loss: 0.6594 - accuracy: 0.7500
Epoch 4/100
1/1 - 0s - loss: 0.6444 - accuracy: 0.7500
Epoch 5/100
1/1 - 0s - loss: 0.6262 - accuracy: 1.0000
Epoch 6/100
1/1 - 0s - loss: 0.6018 - accuracy: 0.7500
Epoch 7/100
1/1 - 0s - loss: 0.5698 - accuracy: 0.7500
Epoch 8/100
1/1 - 0s - loss: 0.5277 - accuracy: 0.7500
Epoch 9/100
1/1 - 0s - loss: 0.4857 - accuracy: 1.0000
Epoch 10/100
1/1 - 0s - loss: 0.4387 - accuracy: 1.0000
Epoch 11/100
1/1 - 0s - loss: 0.3877 - accuracy: 1.0000
Epoch 12/100
1/1 - 0s - loss: 0.3436 - accuracy: 1.0000
Epoch 13/100
1/1 - 0s - loss: 0.2981 - accuracy: 1.0000
Epoch 14/100
1/1 - 0s - loss: 0.2530 - accuracy: 1.0000
Epoch 15/100
1/1 - 0s - loss: 0.2102 - accuracy: 1.0000
Epoch 16/100
1/1 - 0s - loss: 0.1733 - accuracy: 1.0000
Epoch 17/100
1/1 - 0s - loss: 0.1424 - accuracy: 1.0000
Epoch 18/100
1/1 - 0s - loss: 0.1159 - accuracy: 1.0000
E

In [134]:
for i in range(xor_samples.shape[0]):
    print("Previsão para x = ",xor_samples[i])
print('\nPredito x Esperado \n')
print(model_2.predict(xor_samples))
print('\n')
print(xor_labels)

Previsão para x =  [0 1]
Previsão para x =  [1 0]
Previsão para x =  [1 1]
Previsão para x =  [0 0]

Predito x Esperado 

[[9.9936867e-01]
 [9.9933720e-01]
 [1.5522242e-03]
 [1.2347102e-04]]


[[1]
 [1]
 [0]
 [0]]


## b)

### Preparação dos dados

In [172]:
sen_pix_samples = np.arange(0.001,4,0.001)
sen_pix_labels = []

for i in range(sen_pix_samples.shape[0]):
    pix = sen_pix_samples[i]*np.pi
    sen_pix_labels.append([round((np.sin(pix))/pix, 3)])

In [174]:
#Transformar os dados em numpy arrays para inserir na fit function
#Fazer o shuffle para evitar que a rede aprenda a ordem
sen_pix_labels = np.array(sen_pix_labels)
sen_pix_samples = sen_pix_samples.reshape(-1,1)
sen_pix_labels, sen_pix_samples  = shuffle(sen_pix_labels, sen_pix_samples )

[[1.839]
 [1.252]
 [2.717]
 ...
 [2.045]
 [1.599]
 [2.05 ]]


### Modelo

In [166]:
model_3 = Sequential([
    Dense(units=16, input_shape=(1,), activation='sigmoid'),
    Dense(units=8, activation='sigmoid'),  
    Dense(units=8, activation='sigmoid'),    
    Dense(units=1, activation='tanh'),
])

In [155]:
    model_3.summary()

Model: "sequential_14"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_35 (Dense)             (None, 16)                32        
_________________________________________________________________
dense_36 (Dense)             (None, 8)                 136       
_________________________________________________________________
dense_37 (Dense)             (None, 8)                 72        
_________________________________________________________________
dense_38 (Dense)             (None, 1)                 9         
Total params: 249
Trainable params: 249
Non-trainable params: 0
_________________________________________________________________


In [167]:
model_3.compile(optimizer=Adam(learning_rate=0.1), loss='mean_squared_error', metrics=['accuracy'])

In [170]:
model_3.fit(x=sen_pix_samples, y=sen_pix_labels, validation_split=0.2, batch_size=399, epochs=10, shuffle=True, verbose=2)

Epoch 1/10
9/9 - 0s - loss: 5.1297e-04 - accuracy: 0.9991 - val_loss: 3.1957e-04 - val_accuracy: 1.0000
Epoch 2/10
9/9 - 0s - loss: 2.0837e-04 - accuracy: 0.9997 - val_loss: 7.7965e-04 - val_accuracy: 0.9987
Epoch 3/10
9/9 - 0s - loss: 3.1301e-04 - accuracy: 0.9994 - val_loss: 2.6899e-04 - val_accuracy: 1.0000
Epoch 4/10
9/9 - 0s - loss: 1.7782e-04 - accuracy: 1.0000 - val_loss: 4.5496e-04 - val_accuracy: 0.9987
Epoch 5/10
9/9 - 0s - loss: 2.0313e-04 - accuracy: 1.0000 - val_loss: 2.6385e-04 - val_accuracy: 1.0000
Epoch 6/10
9/9 - 0s - loss: 2.0461e-04 - accuracy: 0.9997 - val_loss: 3.0483e-04 - val_accuracy: 1.0000
Epoch 7/10
9/9 - 0s - loss: 1.6947e-04 - accuracy: 1.0000 - val_loss: 4.4511e-04 - val_accuracy: 0.9987
Epoch 8/10
9/9 - 0s - loss: 2.5269e-04 - accuracy: 0.9997 - val_loss: 2.7628e-04 - val_accuracy: 1.0000
Epoch 9/10
9/9 - 0s - loss: 2.1688e-04 - accuracy: 0.9997 - val_loss: 3.9643e-04 - val_accuracy: 0.9987
Epoch 10/10
9/9 - 0s - loss: 3.3987e-04 - accuracy: 0.9994 - val